-- MySQL Script generated by MySQL Workbench
-- Sam 28 Jan 2017 12:02:22 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `tblfitness_event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_event_type` (
  `idevent_type` INT(11) NOT NULL AUTO_INCREMENT,
  `dtname` VARCHAR(127) NOT NULL,
  `dtdescription` TEXT NULL DEFAULT NULL,
  `dtlimit` INT NULL,
  PRIMARY KEY (`idevent_type`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tblfitness_event_subtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_event_subtype` (
  `idevent_subtype` INT NOT NULL AUTO_INCREMENT,
  `fievent_type` INT(11) NOT NULL,
  `dtlabel` VARCHAR(127) NOT NULL,
  PRIMARY KEY (`idevent_subtype`),
  INDEX `fk_tblfitness_event_subtype_tblfitness_event_type1_idx` (`fievent_type` ASC),
  CONSTRAINT `fk_tblfitness_event_subtype_tblfitness_event_type1`
    FOREIGN KEY (`fievent_type`)
    REFERENCES `tblfitness_event_type` (`idevent_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tblfitness_event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_event` (
  `idevent` INT(11) NOT NULL AUTO_INCREMENT,
  `fievent_type` INT(11) NOT NULL,
  `fievent_subtype` INT(11) NULL,
  `dtdate` DATETIME NOT NULL,
  `dtduration` INT(11) NOT NULL,
  `dtarchive` TINYINT(1) NULL DEFAULT '0',
  `dtvisible` TINYINT(1) NULL DEFAULT '0',
  `dtlimit` INT NULL,
  PRIMARY KEY (`idevent`),
  INDEX `fk_tblfitness_event_tblfitness_event_type1_idx` (`fievent_type` ASC),
  INDEX `fk_tblfitness_event_tblfitness_event_subtype1_idx` (`fievent_subtype` ASC),
  CONSTRAINT `fk_tblfitness_event_tblfitness_event_type1`
    FOREIGN KEY (`fievent_type`)
    REFERENCES `tblfitness_event_type` (`idevent_type`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_tblfitness_event_tblfitness_event_subtype1`
    FOREIGN KEY (`fievent_subtype`)
    REFERENCES `tblfitness_event_subtype` (`idevent_subtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tblfitness_mail_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_mail_template` (
  `idtemplate` INT(11) NOT NULL AUTO_INCREMENT,
  `dtname` VARCHAR(63) NOT NULL,
  `dtsubject` VARCHAR(255) NOT NULL,
  `dtcontent` TEXT NOT NULL,
  PRIMARY KEY (`idtemplate`),
  UNIQUE INDEX `dtname` (`dtname` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tblfitness_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `dtlast_name` VARCHAR(63) NOT NULL,
  `dtfirst_name` VARCHAR(63) NOT NULL,
  `dtpassword` TEXT NOT NULL,
  `dttype` ENUM('admin','coach','customer') NOT NULL DEFAULT 'customer',
  `dtemail` VARCHAR(127) NULL,
  `dttel` VARCHAR(20) NOT NULL,
  `dtbirthdate` DATE NULL DEFAULT NULL,
  `dtenabled` TINYINT(1) NOT NULL DEFAULT '0',
  `dtstreet` VARCHAR(127) NULL,
  `dtcity` VARCHAR(127) NULL,
  `dtzip` INT(11) NULL,
  `dtcountry` VARCHAR(127) NULL,
  `dtsubscription` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `dtemail` (`dtemail` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tblfitness_user2event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tblfitness_user2event` (
  `fiuser` INT(11) NOT NULL,
  `fievent` INT(11) NOT NULL,
  `dtsubscription_signature` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`fiuser`, `fievent`),
  INDEX `fk_tbluser2event_tblfitness_event1_idx` (`fievent` ASC),
  CONSTRAINT `fk_tbluser2event_tblfitness_event1`
    FOREIGN KEY (`fievent`)
    REFERENCES `tblfitness_event` (`idevent`),
  CONSTRAINT `fk_tbluser2event_tblfitness_user`
    FOREIGN KEY (`fiuser`)
    REFERENCES `tblfitness_user` (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
